# development:
#   adapter: async
#
# test:
#   adapter: async
#
# production:
#   adapter: redis
#   url: redis://localhost:6379/1

development: &development
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
test: *development
production: &production
  :url: redis://h:pdcf2ea033a7c3d850a1e6c049ea0c26cb0f6510d34c9eb2d907b78ef4c37ad5d@ec2-34-198-54-21.compute-1.amazonaws.com:25159
  :host: ec2-34-198-54-21.compute-1.amazonaws.com
  :port: 25159
  :password: pdcf2ea033a7c3d850a1e6c049ea0c26cb0f6510d34c9eb2d907b78ef4c37ad5d
  :inline: true
  :timeout: 1
